[package]
name = "graph"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
fixedbitset = "0.4.2"
num = "0.4.0"
petgraph = "0.6.3"

[dev-dependencies]
iai = { git = "https://github.com/AlexMikhalev/iai", branch = "memory_usage" }

# [[bench]]
# name = "iai_benchmarks"
# harness = false
