[package]
name = "aigraph1"
version = "0.1.0"
edition = "2021"

description = "Graph serching algorithms"
license = "MIT"
repository = "https://github.com/AOx0/aigraph1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "graph"
path = "lib/lib.rs"

[[bin]]
name = "aigraph1"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.69"
dioxus = { version = "0.3.2", features = ["hot-reload"] }
dioxus-web = "0.3.1"
fixedbitset = "0.4.2"
num = "0.4.0"
petgraph = "0.6.3"
text_io = "0.1.12"
unicase = "2.6.0"

[dev-dependencies]
iai = { git = "https://github.com/AlexMikhalev/iai", branch = "memory_usage" }
criterion = { version = "0.4.0", features = ["html_reports"] }

[[bench]]
name = "iai_benchmarks"
harness = false

[[bench]]
name = "criterion_benchmarks"
harness = false
