name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    name: docs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Install trunk
        uses: jetli/trunk-action@v0.2.0
        with:
          version: 'latest'

      - name: Install tailwindcss binary
        run: |
          curl -sLO https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-amd64
          chmod +x tailwindcss-linux-amd64
          sudo mv tailwindcss-linux-amd64 /usr/local/bin/tailwindcss

      - name: Install wasm32 target
        run: rustup target add wasm32-unknown-unknown

      - name: Cache Cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
            target/debug
            target/release
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build documentation
        run: cargo doc --release

      - name: Build WASM website
        run: env TRUNK_BUILD_PUBLIC_URL="./" trunk build --release

      - name: Copy documentation to dist
        run: |
          mv target/doc/* dist/

      - name: Deploy to target branch
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true